config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  devise_for :users

  resources :beds do
    resources :reservations
  end

  resources :hospices

  get 'console/open_beds', as: 'open_beds'

  get '/public_pages/about', as: 'about'
  get '/public_pages/contact_us', as: 'contact_us'
  get '/public_pages/legal', as: 'legal'
  get '/public_pages/privacy_policy', as: 'privacy_policy'

  root 'public_pages#home'
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bed.rb
class Bed < ApplicationRecord
  belongs_to :hospice
  has_many :reservations

  scope :get_my_beds, ->(hospice) {where("hospice_id = ?", hospice)}
end

app/models/hospice.rb
class Hospice < ApplicationRecord
  has_many :beds
  has_many :users

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :bed
  belongs_to :user

end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reservations       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:public_pages, :open_beds]

end

app/controllers/beds_controller.rb
class BedsController < ApplicationController
  before_action :set_bed, only: [:show, :edit, :update, :destroy]

  def index
    @beds = Bed.all
  end

  def show
  end

  def new
    @bed = Bed.new
  end

  def edit
  end

  def create
    @bed = Bed.new(bed_params)
    @bed.hospice_id=current_user.hospice_id

    respond_to do |format|
      if @bed.save
        format.html { redirect_to @bed, notice: 'Bed was successfully added.' }
        format.json { render :show, status: :created, location: @bed }
      else
        format.html { render :new }
        format.json { render json: @bed.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bed.update(bed_params)
        format.html { redirect_to @bed, notice: 'Bed was successfully updated.' }
        format.json { render :show, status: :ok, location: @bed }
      else
        format.html { render :edit }
        format.json { render json: @bed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bed.destroy
    respond_to do |format|
      format.html { redirect_to beds_url, notice: 'Bed was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def set_bed
      @bed = Bed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bed_params
      params.require(:bed).permit(:hospice_id, :status, :room_type, :bed_type, :gender, :desc)
    end
end

app/controllers/console_controller.rb
class ConsoleController < ApplicationController
  before_action :authenticate_user!, except: :open_beds

  def open_beds
    @open_beds = Bed.where(status: 'open')
    puts @open_beds
  end
end

app/controllers/hospices_controller.rb
class HospicesController < ApplicationController
  before_action :set_hospice, only: [:show, :edit, :update, :destroy]

  def index
    @hospices = Hospice.all
  end

  def show
  end

  def new
    @hospice = Hospice.new
  end

  def edit
  end

  def create
    @hospice = Hospice.new(hospice_params)

    respond_to do |format|
      if @hospice.save
        # # every user needs to have a hospice. user creating hopice is the first admin
        # current_user.hospice_id = @hospice.id
        # current_user.admin = true
        # current_user.save!
        format.html { redirect_to @hospice, notice: 'Hospice was successfully added.' }
        format.json { render :show, status: :created, location: @hospice }
      else
        format.html { render :new }
        format.json { render json: @hospice.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @hospice.update(hospice_params)
        format.html { redirect_to @hospice, notice: 'Hospice was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospice }
      else
        format.html { render :edit }
        format.json { render json: @hospice.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @hospice.destroy
    respond_to do |format|
      format.html { redirect_to hospices_url, notice: 'Hospice was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def set_hospice
      @hospice = Hospice.find(params[:id])
    end

    def hospice_params
      params.require(:hospice).permit(:name, :address1, :address2, :city, :state, :zipcode, :main_phone, :fax, :referral_phone, :description, :bed_owner)
    end
end

app/controllers/public_pages_controller.rb
class PublicPagesController < ApplicationController
  public_pages = [:about, :contact_us, :home, :legal, :privacy_policy]
  before_action :authenticate_user!, :except => public_pages

  def about
  end

  def contact_us
  end

  def home
  end

  def legal
  end

  def privacy_policy
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  def index
    @reservations = Reservation.all
  end

  def show
  end

  def new
    @reservation = Reservation.new
    @bed = params[:bed_id]
  end

  def edit
  end

  def create       
    @reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'A reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    def reservation_params
      params.require(:reservation).permit(:bed_id, :user_id, :reserve_date, :reopen_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beds_helper.rb
module BedsHelper
end

app/helpers/hospices_helper.rb
module HospicesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/beds/_form.html.erb
<%= form_for(bed) do |f| %>
  <% if bed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bed.errors.count, "error") %> prohibited this bed from being saved:</h2>

      <ul>
      <% bed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class=" field form-group">
    <%= f.label :hospice %>
    <%= f.collection_select :hospice_id, Hospice.order(:name), :id, :name %>
  </div>

  <div class=" field form-group">
    <%= f.label :status %>
    <%= f.select :status, ['Open', 'Occupied'], :prompt => 'Select Status', class: "form-control" %>
  </div>

  <div class=" field form-group">
    <%= f.label :room_type %>
    <%= f.select :room_type, ['Private', 'Semi-Private'], :prompt => 'Select Privacy Type', class: "form-control" %>
  </div>

  <div class=" field form-group">
    <%= f.label :bed_type %>
    <%= f.select :bed_type, ['Respite', 'In-Patient'], class: "form-control" %>
  </div>

  <div class=" field form-group">
    <%= f.label :gender %>
    <%= f.select :gender, ['Male', 'Female'], :prompt => 'Select Gender', class: "form-control" %>
  </div>

  <div class=" field form-group">
    <%= f.label :description %>
    <%= f.text_field :desc, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/beds/edit.html.erb
<h1>Editing Bed</h1>

<%= render 'form', bed: @bed %>

<%= link_to 'Show', @bed %> |
<%= link_to 'Back', beds_path %>

app/views/beds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Beds</h1>

<div class="panel-group">
  <div class="hospiceBeds">
    <% @beds.each do |bed| %>
    <div class="hospiceBeds-row">
        <strong><%= bed.hospice.name %></strong>
        <%= bed.status.capitalize %>
        <%= bed.room_type.capitalize %>
        <%= bed.bed_type %>
        <%= bed.gender.capitalize %>
        <%= bed.desc %>
        <%= link_to 'Edit', edit_bed_path(bed) %>
        <%= link_to 'Remove', bed, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'Add a Bed', new_bed_path, class: "btn btn-default"  %>

app/views/beds/new.html.erb
<h1>Add a New Bed</h1>

<%= render 'form', bed: @bed %>

<%= link_to 'Back', beds_path %>

app/views/beds/open_beds.html.erb
<h1>Open Beds</h1>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>Hospice</th>
      <th>Status</th>
      <th>Room type</th>
      <th>Bed type</th>
      <th>Gender</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @open_beds.each do |bed| %>
      <tr>
        <td><%= bed.hospice.name %></td>
        <td><%= bed.status.capitalize %></td>
        <td><%= bed.room_type.capitalize %></td>
        <td><%= bed.bed_type %></td>
        <td><%= bed.gender.capitalize %></td>
        <td><%= bed.desc %></td>
        <td><%= link_to 'Show', bed %></td>
        <td><%= link_to 'Edit', edit_bed_path(bed) %></td>
        <td><%= link_to 'Destroy', bed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/beds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hospice:</strong>
  <%= @bed.hospice.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bed.status.capitalize %>
</p>

<p>
  <strong>Room type:</strong>
  <%= @bed.room_type.capitalize %>
</p>

<p>
  <strong>Bed type:</strong>
  <%= @bed.bed_type.capitalize %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @bed.gender.capitalize %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bed.desc %>
</p>

<%= link_to 'Edit', edit_bed_path(@bed) %> |
<%= link_to 'Back', beds_path %>

app/views/console/open_beds.html.erb
<div class="panel-group" id="accordian">
  <ol class='openBed'>
    <% @open_beds.each do |bed| %>
      <li>
        <div class="panel-heading">

          <strong><%= bed.hospice.name %></strong>
          <br>
          <%if bed.gender.capitalize == "Female"%>
            <i class="fa fa-female"></i>
          <%else%>
            <i class="fa fa-male"></i>
          <%end%>

          <%= bed.room_type.capitalize %>
          <%= bed.bed_type %>
          <br>
          <%= link_to 'RESERVE', new_bed_reservation_path(bed), id: 'button_font', class: "btn btn-success" %><br>
          <a data-toggle="collapse" data-parent="#accordian" href="#collapse<%=bed.id%>">
            <span class="fa fa-arrow-circle-down" onclick="toggleInfo(this)">More Info</span></a>
        </div>

        <div id="collapse<%=bed.id%>" class="panel-collapse collapse out">
          <div class="panel-body">
            <p class="hospiceAddress">
              <%= bed.hospice.name %><br>
              <%= bed.hospice.address1 %><br>

            <%if bed.hospice.address2?%>
              <%= bed.hospice.address2 %><br>
            <%end%>

              <%= bed.hospice.city %>, <%= bed.hospice.state %> <%= bed.hospice.zipcode %>
            </p>

            <p>
              <strong>Phone:</strong>
              <%= bed.hospice.main_phone %>
            </p>

            <p>
              <strong>Fax:</strong>
              <%= bed.hospice.fax %>
            </p>

            <%if bed.hospice.referral_phone?%>
            <p>
              <strong>Referral phone:</strong>
              <%= bed.hospice.referral_phone %>
            </p>
            <%end%>

            <p>
              <strong>Description:</strong>
              <%= bed.hospice.description %>
            </p>

          </div>
        </div>
      </li>
    <% end %>
  </ol>
</div>

app/views/hospices/_form.html.erb
<%= form_for(hospice) do |f| %>
  <% if hospice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hospice.errors.count, "error") %> prohibited this hospice from being saved:</h2>

      <ul>
      <% hospice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :address1 %>
    <%= f.text_field :address1, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :address2 %>
    <%= f.text_field :address2, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :state %>
    <%= f.text_field :state, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :main_phone %>
    <%= f.text_field :main_phone, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :fax %>
    <%= f.text_field :fax, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :referral_phone %>
    <%= f.text_field :referral_phone, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="field form-group">
    <span><strong>Check if this hospice owns beds:&nbsp;</strong></span>
    <%= f.check_box :bed_owner %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hospices/edit.html.erb
<h1>Edit Hospice Information</h1>

<%= render 'form', hospice: @hospice %>

<%= link_to 'Show', @hospice %> |
<%= link_to 'Back', hospices_path %>

app/views/hospices/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'TOP', '#', id: 'toTop' %>

<h1>Hospices</h1>

<%= link_to 'Add Hospice', new_hospice_path, class: "btn btn-success", id: "addHospice" %>

<div class="panel-group" id="accordian">
  <div class="hospices">
    <% @hospices.each do |hospice| %>
      <div class="hospices-row">

        <div class="panel-heading">
          <strong><%= hospice.name %></strong><br>
          <%= button_to 'Edit', edit_hospice_path(hospice), method: :get, class: 'btn btn-info' %>
          <%= button_to 'Remove', hospice, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>

          <a data-toggle="collapse" data-parent="#accordian" href="#collapse<%=hospice.id%>">
          <span class="fa fa-arrow-circle-down" onclick="toggleInfo(this)">More Info</span></a>
        </div>

      <div id="collapse<%=hospice.id%>" class="panel-collapse collapse out">
        <div class="panel-body">

        <p class="hospiceAddress">
        <%= hospice.name %><br>
        <%= hospice.address1 %><br>

        <%if hospice.address2? %>
          <%= hospice.address2 %><br>
        <%end%>

        <%= hospice.city %>, <%= hospice.state %> <%= hospice.zipcode %>
      </p>

      <p>
        <strong>Phone:</strong>
        <%= hospice.main_phone %>
      </p>

      <p>
        <strong>Fax:</strong>
        <%= hospice.fax %>
      </p>

      <%if hospice.referral_phone? %>
      <p>
        <strong>Referral phone:</strong>
        <%= hospice.referral_phone %>
      </p>
      <%end%>

      <p>
        <strong>Description:</strong>
        <%= hospice.description %>
      </p>

      <p>
        <strong>Bed Owner?</strong>
        <%= hospice.bed_owner %>
      </p>
    </div>
    </div>
    </div>
    <% end %>
  </div>
</div>

app/views/hospices/new.html.erb
<h1>Add a New Hospice</h1>

<%= render 'form', hospice: @hospice %>

<%= link_to 'Back', hospices_path %>

app/views/hospices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hospice.name %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @hospice.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @hospice.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @hospice.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @hospice.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @hospice.zipcode %>
</p>

<p>
  <strong>Main phone:</strong>
  <%= @hospice.main_phone %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @hospice.fax %>
</p>

<p>
  <strong>Referral phone:</strong>
  <%= @hospice.referral_phone %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hospice.description %>
</p>

<p>
  <strong>Bed owner:</strong>
  <%= @hospice.bed_owner %>
</p>

<%= link_to 'Edit', edit_hospice_path(@hospice), class: "btn btn-default" %> |
<%= link_to 'Back', hospices_path, class: "btn btn-default" %>

app/views/layouts/_footer.html.erb
<footer id="site-footer" data-turbolinks-permanent>
  <div class="row">
    <h6>
      <section class="center">
        <%= link_to 'Home', root_path, rel: 'prefetch' %> |
        <%= link_to 'Legal ', legal_path %> |
        <%= link_to 'Privacy Policy ', privacy_policy_path %> |
        <%= link_to 'Contact Us', contact_us_path %>
      </section>
    </h6>
    <section class="center">
      <h6>&copy; 2016. HospiceBeds, Inc.  All rights reserved.</h6>
    </section>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= image_tag 'HB.png', title: 'HB', id:'brand' %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path%></li>
        <li><%= link_to "Hospices", hospices_path%></li>
        <li><%= link_to "All Beds", beds_path%></li>
        <li><%= link_to "Open Beds", open_beds_path%></li>
        <li><%= link_to "Reservations", reservations_path%></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to('Logout', destroy_user_session_path(current_user), :method => :delete)%></li>
      </ul> <!-- line 28 -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hospice Beds</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid" id="main">
    <%= render 'layouts/navbar' %>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
<br>
</html>

app/views/public_pages/about.html.erb
<div class='center'>
  <<h2>About Hospice Beds</h2>
</div>

app/views/public_pages/contact_us.html.erb
<div class='center'>
  <h2>Contact Us</h2>
</div>

app/views/public_pages/home.html.erb
<div class="landingPage">
    <h2><em><%= link_to 'View Beds', open_beds_path %> | <%= link_to 'Login', user_session_path, method: 'get' %><em></h2>
</div>

app/views/public_pages/legal.html.erb
<div class='center'>
  <h2>Legal Stuff</h2>
</div>

app/views/public_pages/privacy_policy.html.erb
<div class='center'>
  <h2>Privacy Policy</h2>
</div>

app/views/reservations/_form.html.erb
<%= form_for(reservation) do |f| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :bed_id, value: @bed %>
  <%= f.hidden_field :user_di, value: current_user %>

  <div class="field form-group">
    <%= f.label :reserve_date %>
    <%= f.date_select :reserve_date, class: "form-control" %>
  </div>
  <br>
  <p>Complete this field only if you know the exact length of the patient's stay.  Otherwise leave blank.</p>
  <div class="field form-group">
    <%= f.label :reopen_date %>
    <%= f.date_select :reopen_date, class: "form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit id: "submitReservation" %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Edit Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h2>Your Open Reservations</h2>

<div class="panel-group">
    <div class='reservationBed'>
    <% @reservations.each do |reservation| %>
      <div class = "reservationBeds-row">
        <%= reservation.bed.hospice.name %>
        <br>
        <%if reservation.bed.gender.capitalize == "Female"%>
            <i class="fa fa-female"></i>
        <%else%>
            <i class="fa fa-male"></i>
        <%end%>

        <%= reservation.bed.room_type %>
        <%= reservation.bed.bed_type %>
        <%= reservation.reserve_date %>
        <% if reservation.reopen_date? %>
          to <%= reservation.reopen_date %>
        <%end%>

        <%= link_to 'Edit', edit_reservation_path(reservation) %>
        <%= link_to 'Cancel', reservation, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
    </div>
</div>
<%= link_to 'View Open Beds', open_beds_path %>

app/views/reservations/new.html.erb
<div class = "reservationForm">
<h1>Pending Reservation</h1>
<h4>Complete this form to temporarily reserve a bed.</h4>
<h4>The bed will be held for one hour until the reservation is completed by phone or fax.</h4>
<br>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path, class: "btn btn-danger", id: "backBtn" %>
</div>

app/views/reservations/show.html.erb
<br>
<h2>Complete Your Reservation in One Hour</h2>
<h4>Reservations not completed and verified by the hospice within an hour are canceled automatically.</h4>
<br>
<div class='container'>
  <h4><div class='pull-left'>
    <%= @reservation.bed.hospice.name%><br>
    <%= @reservation.bed.hospice.address1%><br>
    <%= @reservation.bed.hospice.address2 %><br>
    <%= @reservation.bed.hospice.city %>, 
    <%= @reservation.bed.hospice.state %>&nbsp;
    <%= @reservation.bed.hospice.zipcode %>
  </div>
  <div class='center'>
    Main Phone: <%= @reservation.bed.hospice.main_phone%><br>
    Fax: <%= @reservation.bed.hospice.fax%><br>
    Referral Phone: <%= @reservation.bed.hospice.referral_phone%>
  </div>
  <br><br>
  <div>
    <strong>Bed:</strong>
    <%= @reservation.bed.desc %>
  </div>
  <br>
  <div>
    <strong>Reserve date:</strong>
    <%= @reservation.reserve_date %>
  </div>
  <div>
    <strong>Reopen date:</strong>
    <%= @reservation.reopen_date %>
  </div></h4>
  <br>
  <!-- NOT SURE BUTTONS ARE THE WAY TO GO HERE! -->
  <div>
    <div class='pull-left'>
      <%= link_to 'Cancel Reservation', reservation_path(@reservation), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", id: "backBtn" %>
    </div>
    <div class='pull-left'>
      <%= link_to 'Edit Dates', edit_reservation_path(@reservation), class: 'btn btn', id: 'editReservation' %>
    </div>
    <div class='pull-left'>  
      <%= link_to 'View Your Reservations', reservations_path, class: 'btn btn', id: 'viewReservation' %>
    </div>  
  </div>
</div>